FROM webhippie/alpine:latest-amd64@sha256:7fefa6e1e15474891fe5f35455516bdf3fd06a75efee109e4ced2e45d78ff0a4 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="HetznerCloud Exporter" \
  org.opencontainers.image.documentation="https://promhippie.github.io/hcloud_exporter/" \
  org.opencontainers.image.vendor="Thomas Boerger"

EXPOSE 9501
ENTRYPOINT ["/usr/bin/hcloud_exporter"]
HEALTHCHECK CMD ["/usr/bin/hcloud_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/hcloud_exporter /usr/bin/hcloud_exporter
