FROM arm32v6/alpine:3.16@sha256:269d2ad7050b30a9ea100b3780a868ee30a165f9d098f3030120a1d87697f40c AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9501
ENTRYPOINT ["/usr/bin/hcloud_exporter"]
HEALTHCHECK CMD ["/usr/bin/hcloud_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/hcloud_exporter /usr/bin/hcloud_exporter
