FROM arm64v8/alpine:3.20@sha256:1c3b93ed450e26eac89b471d6d140e2f99488f489739b8b8ea5e8202dd086f82 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9501
ENTRYPOINT ["/usr/bin/hcloud_exporter"]
HEALTHCHECK CMD ["/usr/bin/hcloud_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/hcloud_exporter /usr/bin/hcloud_exporter
