FROM arm32v6/alpine:3.22@sha256:1b418ed7e714de83d1340852aa0127c4b0a20f70dd4af970e452a2dc06979f98 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9501
ENTRYPOINT ["/usr/bin/hcloud_exporter"]
HEALTHCHECK CMD ["/usr/bin/hcloud_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/hcloud_exporter /usr/bin/hcloud_exporter
