FROM arm32v6/alpine:3.16@sha256:5da989a9a3a08357bc7c00bd46c3ed782e1aeefc833e0049e6834ec1dcad8a42 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9501
ENTRYPOINT ["/usr/bin/hcloud_exporter"]
HEALTHCHECK CMD ["/usr/bin/hcloud_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/hcloud_exporter /usr/bin/hcloud_exporter
